#!/bin/sh

set -e

cd "$(dirname $(realpath "$0"))"

basedir="bernhackt2018-aldente-backend/proto/tdi"

# build () {
# 	pbjs -t static-module --sparse -w commonjs "$basedir/$1" >"$2"
# }

# set -x

# build VersionTdiArray.proto pbf/VersionTDI.js
# build StopTdiArray.proto pbf/StopTDI.js
# build StopPointTdiArray.proto pbf/StopPointTDI.js
# build RouteTdiArray.proto pbf/RouteTDI.js
# build PatternTdiArray.proto pbf/PatternTDI.js
# build StopPassageTdiArray.proto pbf/StopPassageTDI.js
# build VehicleTdiArray.proto pbf/VehicleTDI.js
# build PassengerAlertTdiArray.proto pbf/PassengerAlertTDI.js

# Workaround because, with the setup above, each file generated by
# protobuf.js overwrites a shared global object. 🙄
# todo: use protocol-buffers or pbf once they support imports

pbjs -t static-module -w commonjs -p $basedir \
	"$basedir/VersionTdiArray.proto" \
	"$basedir/StopTdiArray.proto" \
	"$basedir/StopPointTdiArray.proto" \
	"$basedir/RouteTdiArray.proto" \
	"$basedir/PatternTdiArray.proto" \
	"$basedir/StopPassageTdiArray.proto" \
	"$basedir/VehicleTdiArray.proto" \
	"$basedir/PassengerAlertTdiArray.proto" \
	>pbf/index.js
